apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka-broker
spec:
  ports:
  - port: 9092
  selector:
    app: kafka-broker

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker
  labels:
    app: kafka-broker
spec:
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
      - name: kafka-broker
        image: docker.io/bitnami/kafka:3.3
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-service.default.svc.cluster.local:9092
