kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper-deploy
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zoo1
        image: docker.io/bitnami/zookeeper:3.8
        ports:
        - containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"          

---

apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zookeeper
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  selector:
    app: zookeeper
